name: Build Mace Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Setup Gradle 4.10.3
      run: |
        wget https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
        unzip -d opt gradle-4.10.3-bin.zip
        echo "$(pwd)/opt/gradle-4.10.3/bin" >> $GITHUB_PATH
    - name: Build with Gradle
      run: |
        gradle build --stacktrace
    - name: Save Mod File
      uses: actions/upload-artifact@v4
      with:
        name: MyMaceMod
        path: build/libs/*.jar
